const KEY='leefplanner-v1';
const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const today=iso(new Date()); const plus=(date,n)=>{let d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)};
const dayName=d=>new Intl.DateTimeFormat('nl-BE',{weekday:'long',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const seed=()=>({role:'parent',pin:'1977',dailyLimit:150,people:['Persoon 1','Persoon 2','Persoon 3'],meals:['Spaghetti','Wraps','Lasagne','Pizza','Wok','Soep met brood','Frietjes'],mealPlan:{},tasks:[
{id:crypto.randomUUID(),title:'Keuken opruimen',type:'daily',minutes:15,freq:'Dagelijks',date:today,done:false,spent:null},
{id:crypto.randomUUID(),title:'Vaatwasser leegmaken',type:'daily',minutes:10,freq:'Dagelijks',date:today,done:false,spent:null},
{id:crypto.randomUUID(),title:'Badkamer poetsen',type:'extra',minutes:30,freq:'Wekelijks',date:plus(today,1),done:false,spent:null},
{id:crypto.randomUUID(),title:'Stofzuigen',type:'extra',minutes:25,freq:'Wekelijks',date:today,done:false,spent:null}],
hobbies:[{id:crypto.randomUUID(),title:'Tennis',date:plus(today,1),minutes:60},{id:crypto.randomUUID(),title:'Paaldansen',date:plus(today,3),minutes:75}],
forgotten:defaultForgotten()});
function defaultForgotten(){return {'Keuken & toestellen':['Koffiezet ontkalken','Filter dampkap reinigen','Koelkast poetsen','Diepvries ontdooien','Vaatwasserfilter reinigen','Oven reinigen','Voorraadkast vervaldata nakijken'],'Woning & veiligheid':['Rookmelders testen','Ventilatieroosters reinigen','Radiatoren ontluchten','Waterontharder zout controleren','Afvoerputjes reinigen','Brandblusser controleren','Meterstanden noteren'],'Textiel & kamers':['Dekbed wassen','Matras draaien','Kussens wassen','Gordijnen wassen','Kledingkast seizoenswissel','Schoenen sorteren'],'Administratie':['Verzekeringen nakijken','Energiecontract vergelijken','Belastingdocumenten bewaren','Mutualiteit indienen','Schoolfacturen controleren','Abonnementen opzeggen of verlengen','Paswoorden en back-upcodes bewaren'],'Gezondheid & verzorging':['Tandarts plannen','Oogcontrole plannen','Medicatievoorraad controleren','Contactlenzen bestellen','EHBO-set aanvullen','Zonnecrème vervaldatum controleren'],'Auto & fiets':['Bandenspanning controleren','Ruitensproeiervloeistof aanvullen','Keuring plannen','Onderhoud plannen','Fietsbanden oppompen','Fietsverlichting controleren'],'Tuin & buiten':['Dakgoot controleren','Terras reinigen','Planten snoeien','Tuinmeubilair onderhouden','Buitenkranen winterklaar maken','Grasmaaier onderhouden'],'Digitaal & persoonlijk':['Foto’s back-uppen','Smartphone opschonen','Computerbestanden back-uppen','Verjaardagen en cadeaus plannen','Vakantiepapieren controleren','Noodcontacten actualiseren'],'Kinderen & school':['Sportinschrijving vernieuwen','Oudercontact noteren','Schoolkalender controleren','Kledij en schoenen op maat controleren','Bibliotheekboeken terugbrengen','Identiteitsdocumenten controleren']};}
let state=JSON.parse(localStorage.getItem(KEY)||'null')||seed();
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function ensureWeek(){for(let i=0;i<7;i++){let d=plus(today,i);if(!state.mealPlan[d])state.mealPlan[d]={meal:'',eaters:[]};}}
function render(){ensureWeek();renderNav();renderDashboard();renderMeals();renderTasks();renderForgotten();renderSettings();localStorage.setItem(KEY,JSON.stringify(state));}
function renderNav(){const child=state.role==='child';$$('#nav button').forEach(b=>{b.style.display=child&&b.dataset.tab!=='meals'?'none':''});$('#roleBtn').textContent=child?'Oudermodus':'Kindermodus';if(child)switchTab('meals');}
function switchTab(id){$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
$$('#nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function renderDashboard(){let ts=state.tasks.filter(t=>t.date===today), done=ts.filter(t=>t.done), planned=ts.reduce((a,t)=>a+t.minutes,0), spent=done.reduce((a,t)=>a+(t.spent??t.minutes),0), pct=ts.length?Math.round(done.length/ts.length*100):100;$('#todayTitle').textContent=dayName(today);$('#daySummary').innerHTML=pct===100?`<div class="metric">✓ 100% voltooid</div><p>Alle taken afgerond · ${spent} min besteed</p><div class="progress"><span style="width:100%"></span></div>`:`<div class="metric">${pct}% voltooid</div><p>${done.length} van ${ts.length} taken · ${planned} min gepland</p><div class="progress"><span style="width:${pct}%"></span></div>`;$('#todayTasks').innerHTML=ts.length?ts.map(taskHtml).join(''):'<p class="muted">Geen taken gepland.</p>';let m=state.mealPlan[today];$('#todayMeal').innerHTML=m?.meal?`<p class="metric">${esc(m.meal)}</p><p>${1+m.eaters.length} eter(s), jezelf inbegrepen</p>`:'<p class="muted">Nog geen maaltijd gekozen.</p>';}
function taskHtml(t){return `<div class="task ${t.type} ${t.done?'done':''} ${!t.done&&t.date<today?'overdue':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}',this.checked)"><div><strong>${esc(t.title)}</strong><br><small>${t.minutes} min · ${esc(t.freq)}${t.done?` · ${t.spent??t.minutes} min besteed`:''}</small></div></div>`}
window.toggleTask=(id,done)=>{let t=state.tasks.find(x=>x.id===id);t.done=done;if(done){let ans=prompt('Hoeveel minuten heb je eraan besteed?',t.minutes);t.spent=Math.max(0,Number(ans)||t.minutes)}else t.spent=null;save()};
function renderMeals(){$('#mealWeek').innerHTML=[0,1,2,3,4,5,6].map(i=>{let d=plus(today,i),m=state.mealPlan[d];return `<article class="day-card ${d===today?'today':''}"><small>${d===today?'Vandaag':''}</small><h3>${dayName(d)}</h3><label>Gerecht<select onchange="setMeal('${d}',this.value)"><option value="">Nog kiezen</option>${state.meals.map(x=>`<option ${x===m.meal?'selected':''}>${esc(x)}</option>`).join('')}</select></label><button class="secondary" onclick="quickMeal('${d}')">Nieuw gerecht</button><p class="meal-title">Wie eet mee?</p><label class="person-check"><input type="checkbox" checked disabled> Ikzelf</label>${state.people.map(p=>`<label class="person-check"><input type="checkbox" ${m.eaters.includes(p)?'checked':''} onchange="toggleEater('${d}','${attr(p)}',this.checked)"> ${esc(p)}</label>`).join('')}<p><strong>${1+m.eaters.length} eter(s)</strong></p></article>`}).join('');$('#mealLibrary').innerHTML=state.meals.map(m=>`<span class="chip">${esc(m)}</span>`).join('')}
window.setMeal=(d,v)=>{state.mealPlan[d].meal=v;save()};window.toggleEater=(d,p,on)=>{let a=state.mealPlan[d].eaters;a=on?[...new Set([...a,p])]:a.filter(x=>x!==p);state.mealPlan[d].eaters=a;save()};window.quickMeal=d=>openMeal(d);
function renderTasks(){let dates=[...new Set(state.tasks.map(t=>t.date))].sort();$('#taskList').innerHTML=dates.map(d=>{let a=state.tasks.filter(t=>t.date===d),complete=a.length&&a.every(t=>t.done),spent=a.reduce((s,t)=>s+(t.done?(t.spent??t.minutes):0),0);return `<section class="day-group"><div class="day-heading"><h3>${dayName(d)}</h3>${complete?`<span class="complete">✓ 100% · ${spent} min</span>`:`<span class="muted">${a.filter(t=>!t.done).length} open · ${a.filter(t=>!t.done).reduce((s,t)=>s+t.minutes,0)} min</span>`}</div>${a.map(t=>`<div class="task ${t.type} ${t.done?'done':''} ${!t.done&&d<today?'overdue':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}',this.checked)"><div><strong>${esc(t.title)}</strong><br><small>${t.minutes} min · ${esc(t.freq)}${t.done?` · ${t.spent??t.minutes} min besteed`:''}</small></div><div class="task-actions"><button class="secondary" onclick="editTask('${t.id}')">Bewerk</button><button class="secondary" onclick="deleteTask('${t.id}')">×</button></div></div>`).join('')}</section>`}).join('')||'<p class="muted">Nog geen taken.</p>'}
function renderForgotten(){$('#forgottenList').innerHTML=Object.entries(state.forgotten).map(([cat,items])=>`<section class="category"><h3>${esc(cat)}</h3>${items.map(x=>`<div class="forgotten-item"><span>${esc(x)}</span><button onclick="planForgotten('${attr(x)}')">Inplannen</button></div>`).join('')}</section>`).join('')}
window.planForgotten=title=>openTask(null,title);window.deleteTask=id=>{state.tasks=state.tasks.filter(x=>x.id!==id);save()};window.editTask=id=>openTask(id);
function renderSettings(){$('#dailyLimit').value=state.dailyLimit;$('#parentPin').value=state.pin;$('#peopleSettings').innerHTML=state.people.map((p,i)=>`<div class="person-row"><span>${esc(p)}</span><button class="secondary" onclick="removePerson(${i})">Verwijder</button></div>`).join('');$('#hobbySettings').innerHTML=state.hobbies.map((h,i)=>`<div class="hobby-row"><span>${esc(h.title)} · ${dayName(h.date)} · ${h.minutes} min</span><button class="secondary" onclick="removeHobby(${i})">×</button></div>`).join('')}
window.removePerson=i=>{let p=state.people[i];state.people.splice(i,1);Object.values(state.mealPlan).forEach(m=>m.eaters=m.eaters.filter(x=>x!==p));save()};window.removeHobby=i=>{state.hobbies.splice(i,1);save()};
const modal=$('#modal');function showModal(title,body,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;modal.showModal();$('#modalForm').onsubmit=e=>{e.preventDefault();if(e.submitter?.value==='cancel'){modal.close();return}onSave(new FormData(e.currentTarget));modal.close()}}
function openMeal(date=null){showModal('Nieuw gerecht',`<label>Titel<input name="title" required placeholder="Bijv. spaghetti"></label><label><input type="checkbox" name="use" checked> Meteen kiezen voor deze dag</label>`,fd=>{let x=fd.get('title').trim();if(!state.meals.some(m=>m.toLowerCase()===x.toLowerCase()))state.meals.push(x);if(date&&fd.get('use'))state.mealPlan[date].meal=x;save()})}
function openTask(id=null,prefill=''){let t=state.tasks.find(x=>x.id===id);showModal(t?'Taak bewerken':'Taak toevoegen',`<label>Taak<input name="title" required value="${attr(t?.title||prefill)}"></label><div class="grid two"><label>Type<select name="type"><option value="daily" ${t?.type==='daily'?'selected':''}>Dagelijks (grijs)</option><option value="extra" ${t?.type!=='daily'?'selected':''}>Extra (zwart)</option></select></label><label>Tijd (min)<input name="minutes" type="number" min="1" value="${t?.minutes||30}" required></label></div><div class="grid two"><label>Frequentie<select name="freq">${['Eenmalig','Dagelijks','Wekelijks','Tweewekelijks','Maandelijks','Per kwartaal','Jaarlijks'].map(x=>`<option ${x===(t?.freq||'Wekelijks')?'selected':''}>${x}</option>`).join('')}</select></label><label>Datum<input name="date" type="date" value="${t?.date||today}" required></label></div>`,fd=>{let data=Object.fromEntries(fd);if(t)Object.assign(t,data,{minutes:Number(data.minutes)});else state.tasks.push({id:crypto.randomUUID(),...data,minutes:Number(data.minutes),done:false,spent:null});save()})}
$('#addMealBtn').onclick=()=>openMeal();$('#addTaskBtn').onclick=()=>openTask();
$('#addForgottenBtn').onclick=()=>showModal('Geheugensteun toevoegen',`<label>Categorie<input name="cat" required placeholder="Bijv. Huis"></label><label>Taak<input name="title" required></label>`,fd=>{let c=fd.get('cat').trim(),t=fd.get('title').trim();(state.forgotten[c]??=[]).push(t);save()});
$('#addPersonBtn').onclick=()=>{let x=$('#newPerson').value.trim();if(x&&!state.people.includes(x)){state.people.push(x);$('#newPerson').value='';save()}};
$('#dailyLimit').onchange=e=>{state.dailyLimit=Number(e.target.value)||150;save()};$('#parentPin').onchange=e=>{state.pin=e.target.value;save()};
$('#addHobbyBtn').onclick=()=>showModal('Hobby toevoegen',`<label>Naam<input name="title" required></label><div class="grid two"><label>Datum<input name="date" type="date" value="${today}" required></label><label>Tijd (min)<input name="minutes" type="number" min="1" value="60" required></label></div>`,fd=>{let x=Object.fromEntries(fd);state.hobbies.push({...x,id:crypto.randomUUID(),minutes:Number(x.minutes)});save()});
$('#roleBtn').onclick=()=>{if(state.role==='parent'){state.role='child';save()}else{let p=prompt('Geef de oudercode in');if(p===state.pin){state.role='parent';save()}else toast('Onjuiste code')}};
$('#autoPlanBtn').onclick=()=>{let overdue=state.tasks.filter(t=>!t.done&&t.date<today).sort((a,b)=>a.date.localeCompare(b.date)),moved=0;for(const t of overdue){for(let i=0;i<14;i++){let d=plus(today,i),used=state.tasks.filter(x=>x.date===d&&!x.done).reduce((s,x)=>s+x.minutes,0)+state.hobbies.filter(h=>h.date===d).reduce((s,h)=>s+h.minutes,0);if(used+t.minutes<=state.dailyLimit){t.date=d;moved++;break}}}$('#planResult').textContent=moved?`${moved} achterstallige taak/taken verplaatst naar de eerstvolgende passende dag.`:'Geen achterstallige taken om te verplaatsen.';save()};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='leefplanner-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();toast('Back-up geïmporteerd')}catch{toast('Dit bestand kon niet worden geïmporteerd')}};
$('#resetBtn').onclick=()=>{if(confirm('Alle lokale gegevens vervangen door voorbeeldgegevens?')){state=seed();save()}};
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(x=''){return esc(x).replace(/`/g,'&#96;')}
render();
