const KEY='weekkompas-v1';
const DAYS=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
const FREQ={daily:['Dagelijks',1],weekly:['Wekelijks',7],biweekly:['Tweewekelijks',14],monthly:['Maandelijks',30],quarterly:['Trimestrieel',91],semiannual:['Halfjaarlijks',182],yearly:['Jaarlijks',365]};
const demo=()=>({settings:{weekType:'kinderen',alternate:true,capacities:[25,35,20,35,45,120,60]},tasks:[
{id:uid(),name:'Vaatwasser en keuken reset',category:'Keuken',duration:15,frequency:'daily',priority:3,lastDone:null,withKids:true,withoutKids:true,notes:''},
{id:uid(),name:'Was draaien en ophangen',category:'Was',duration:20,frequency:'biweekly',priority:2,lastDone:null,withKids:true,withoutKids:true,notes:''},
{id:uid(),name:'Badkamer poetsen',category:'Poetsen',duration:30,frequency:'weekly',priority:2,lastDone:null,withKids:true,withoutKids:true,notes:''},
{id:uid(),name:'Stofzuigen beneden',category:'Poetsen',duration:25,frequency:'weekly',priority:2,lastDone:null,withKids:true,withoutKids:true,notes:''},
{id:uid(),name:'Papierwerk en administratie',category:'Administratie',duration:30,frequency:'monthly',priority:2,lastDone:null,withKids:false,withoutKids:true,notes:'Bij voorkeur in een kindvrije week'},
{id:uid(),name:'Diepvries controleren',category:'Keuken',duration:20,frequency:'quarterly',priority:1,lastDone:null,withKids:true,withoutKids:true,notes:''}],plans:{},history:[]});
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
let data=load(); let deferredPrompt;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||demo()}catch{return demo()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
const el=id=>document.getElementById(id); const iso=d=>{let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
function startMonday(d=new Date()){d=new Date(d);let day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(12,0,0,0);return d}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function fmt(d){return new Intl.DateTimeFormat('nl-BE',{day:'numeric',month:'short'}).format(new Date(d))}
function weekKey(d){return iso(startMonday(d))}
function currentWeekType(date){if(!data.settings.alternate)return data.settings.weekType;let now=startMonday(new Date()), target=startMonday(date), diff=Math.round((target-now)/604800000);if(Math.abs(diff)%2===0)return data.settings.weekType;return data.settings.weekType==='kinderen'?'kindvrij':'kinderen'}
function isDue(t,date){if(t.frequency==='daily')return true;if(!t.lastDone)return true;let diff=Math.floor((new Date(date)-new Date(t.lastDone))/86400000);return diff>=FREQ[t.frequency][1]}
function overdueDays(t,date){if(!t.lastDone)return FREQ[t.frequency][1];return Math.max(0,Math.floor((new Date(date)-new Date(t.lastDone))/86400000)-FREQ[t.frequency][1])}
function eligible(t,type){return type==='kinderen'?t.withKids:t.withoutKids}
function generatePlan(){let start=new Date(el('weekStart').value+'T12:00:00'), type=el('planWeekType').value, key=weekKey(start);let slots=data.settings.capacities.map((cap,i)=>({date:iso(addDays(start,i)),cap,used:0,tasks:[]}));let candidates=[];data.tasks.filter(t=>eligible(t,type)).forEach(t=>{if(t.frequency==='daily'){slots.forEach(s=>candidates.push({task:t,target:s.date,daily:true,score:100+t.priority*10}))}else if(isDue(t,start))candidates.push({task:t,target:null,daily:false,score:t.priority*30+Math.min(60,overdueDays(t,start))})});candidates.sort((a,b)=>b.score-a.score||a.task.duration-b.task.duration);
let unscheduled=[];for(let c of candidates){let possible=slots.filter(s=>(!c.daily||s.date===c.target)&&s.cap-s.used>=c.task.duration).sort((a,b)=>(b.cap-b.used)-(a.cap-a.used));if(possible.length){let s=possible[possible.length-1];s.tasks.push({entryId:uid(),taskId:c.task.id,status:'planned'});s.used+=c.task.duration}else unscheduled.push(c.task.id)}data.plans[key]={start:key,type,days:slots,unscheduled:[...new Set(unscheduled)]};save();toast('Je weekplan is aangemaakt.')}
function renderAll(){renderDashboard();renderTasks();renderPlan();renderHistory();renderSettings()}
function plannedTaskCard(entry,date){let t=data.tasks.find(x=>x.id===entry.taskId);if(!t)return '';let done=entry.status==='done';return `<div class="taskcard ${done?'done':''}"><div class="tasktop"><span class="taskname">${esc(t.name)}</span><span>${t.duration} min</span></div><div class="meta">${esc(t.category)}</div><div class="mini-actions">${done?'<button data-undo="'+entry.entryId+'" data-date="'+date+'">Heropen</button>':'<button class="primary" data-done="'+entry.entryId+'" data-date="'+date+'">Gedaan</button><button data-move="'+entry.entryId+'" data-date="'+date+'">Morgen</button>'}</div></div>`}
function renderPlan(){let input=el('weekStart');if(!input.value)input.value=weekKey(new Date());el('planWeekType').value=currentWeekType(input.value);let p=data.plans[weekKey(input.value)], grid=el('weekGrid'), warn=el('planWarnings');if(!p){grid.innerHTML='<div class="card">Nog geen planning voor deze week. Klik op <strong>Planning genereren</strong>.</div>';warn.innerHTML='';return}el('planWeekType').value=p.type;grid.innerHTML=p.days.map((d,i)=>`<div class="day"><h3>${DAYS[i]}</h3><div class="cap">${fmt(d.date)} · ${d.used}/${d.cap} min</div>${d.tasks.map(x=>plannedTaskCard(x,d.date)).join('')||'<p class="muted">Rust / vrije ruimte</p>'}</div>`).join('');warn.innerHTML=p.unscheduled.length?`<div class="warning"><strong>${p.unscheduled.length} taak/taken passen niet.</strong> Verhoog je capaciteit of verschuif minder dringende taken.</div>`:''}
function renderDashboard(){let key=weekKey(new Date()),p=data.plans[key],type=p?.type||currentWeekType(new Date());el('weekBadge').textContent=type==='kinderen'?'Kinderweek':'Kindvrije week';el('weekTitle').textContent='Jouw haalbare week';let entries=p?p.days.flatMap(d=>d.tasks.map(x=>({...x,date:d.date}))):[],done=entries.filter(x=>x.status==='done').length,totalMin=entries.reduce((s,e)=>s+(data.tasks.find(t=>t.id===e.taskId)?.duration||0),0);el('weekSummary').textContent=p?`${entries.length} taken ingepland, samen ${Math.floor(totalMin/60)}u${String(totalMin%60).padStart(2,'0')}.`:'Genereer je weekplanning om mentale ruimte te maken.';el('stats').innerHTML=stat(entries.length,'gepland')+stat(done,'afgerond')+stat(entries.length?Math.round(done/entries.length*100)+'%':'0%','vooruitgang')+stat(p?.unscheduled.length||0,'niet ingepland');let today=iso(new Date()),tod=p?.days.find(d=>d.date===today);el('todayTasks').innerHTML=tod?.tasks.length?tod.tasks.map(x=>plannedTaskCard(x,today)).join(''):'<p class="muted">Geen huishoudtaken gepland voor vandaag.</p>';let due=data.tasks.filter(t=>eligible(t,type)&&isDue(t,new Date())).sort((a,b)=>b.priority-a.priority).slice(0,4);el('attention').innerHTML=due.length?due.map(t=>`<div class="taskrow"><div class="grow"><strong>${esc(t.name)}</strong><div class="meta">${FREQ[t.frequency][0]} · ${t.duration} min</div></div></div>`).join(''):'<p class="muted">Alles is onder controle.</p>'}
function stat(v,l){return `<div class="stat"><strong>${v}</strong><span>${l}</span></div>`}
function renderTasks(){let q=el('taskSearch').value.toLowerCase(),cat=el('categoryFilter').value,cats=[...new Set(data.tasks.map(t=>t.category))].sort();el('categoryFilter').innerHTML='<option value="">Alle categorieën</option>'+cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('');let list=data.tasks.filter(t=>(t.name+' '+t.category).toLowerCase().includes(q)&&(!cat||t.category===cat));el('taskList').innerHTML=list.length?list.map(t=>`<div class="card taskrow"><div class="grow"><strong>${esc(t.name)}</strong><div class="meta">${esc(t.category)} · ${FREQ[t.frequency][0]} · ${t.duration} min · prioriteit ${['','laag','normaal','hoog'][t.priority]}</div>${t.notes?`<div class="meta">${esc(t.notes)}</div>`:''}</div><span class="pill">${t.withKids&&t.withoutKids?'elke week':t.withKids?'kinderweek':'kindvrij'}</span><button data-edit="${t.id}">Bewerk</button></div>`).join(''):'<div class="card">Geen taken gevonden.</div>'}
function renderHistory(){let done=data.history.filter(h=>h.action==='done');let mins=done.reduce((s,h)=>s+(h.duration||0),0);el('historyStats').innerHTML=stat(done.length,'voltooid')+stat(Math.floor(mins/60)+'u'+String(mins%60).padStart(2,'0'),'geregistreerd')+stat(data.history.filter(h=>h.action==='moved').length,'doorgeschoven')+stat(data.tasks.length,'actieve taken');el('historyList').innerHTML=data.history.length?data.history.slice().reverse().slice(0,60).map(h=>`<div class="taskrow"><div><strong>${esc(h.taskName)}</strong><div class="meta">${h.action==='done'?'Voltooid':'Doorgeschoven'} · ${new Intl.DateTimeFormat('nl-BE',{dateStyle:'medium'}).format(new Date(h.date))}</div></div></div>`).join(''):'<p class="muted">Nog geen historiek.</p>'}
function renderSettings(){el('currentWeekType').value=data.settings.weekType;el('alternateWeeks').checked=data.settings.alternate;el('capacityInputs').innerHTML=DAYS.map((d,i)=>`<label>${d.slice(0,2)}<input data-cap="${i}" type="number" min="0" max="480" step="5" value="${data.settings.capacities[i]}"></label>`).join('')}
function openTask(id){let t=id?data.tasks.find(x=>x.id===id):null;el('modal').classList.remove('hidden');el('modalTitle').textContent=t?'Taak bewerken':'Nieuwe taak';el('taskId').value=t?.id||'';el('taskName').value=t?.name||'';el('taskCategory').value=t?.category||'Poetsen';el('taskDuration').value=t?.duration||30;el('taskFrequency').value=t?.frequency||'weekly';el('taskPriority').value=t?.priority||2;el('taskLastDone').value=t?.lastDone||'';el('taskWithKids').checked=t?.withKids??true;el('taskWithoutKids').checked=t?.withoutKids??true;el('taskNotes').value=t?.notes||'';el('deleteTask').classList.toggle('hidden',!t)}
function closeTask(){el('modal').classList.add('hidden')}
function completeEntry(entryId,date,undo=false){let p=data.plans[weekKey(date)],entry=p?.days.flatMap(d=>d.tasks).find(e=>e.entryId===entryId),t=data.tasks.find(x=>x.id===entry?.taskId);if(!entry||!t)return;entry.status=undo?'planned':'done';if(!undo){t.lastDone=date;data.history.push({id:uid(),taskId:t.id,taskName:t.name,duration:t.duration,date:new Date().toISOString(),action:'done'})}save()}
function moveEntry(entryId,date){let p=data.plans[weekKey(date)],from=p.days.find(d=>d.tasks.some(e=>e.entryId===entryId)),entry=from?.tasks.find(e=>e.entryId===entryId),t=data.tasks.find(x=>x.id===entry?.taskId);if(!from||!t)return;let idx=p.days.indexOf(from),to=p.days[idx+1];if(!to){toast('Zondag kan niet verder verschoven worden.');return}if(to.used+t.duration>to.cap){toast('Morgen heeft onvoldoende vrije tijd.');return}from.tasks=from.tasks.filter(e=>e.entryId!==entryId);from.used-=t.duration;to.tasks.push(entry);to.used+=t.duration;data.history.push({id:uid(),taskId:t.id,taskName:t.name,duration:t.duration,date:new Date().toISOString(),action:'moved'});save();toast('Taak naar morgen verschoven.')}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m){el('toast').textContent=m;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2200)}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b))}if(b.id==='newTask')openTask();if(b.id==='closeModal'||b.id==='cancelTask')closeTask();if(b.dataset.edit)openTask(b.dataset.edit);if(b.dataset.done)completeEntry(b.dataset.done,b.dataset.date);if(b.dataset.undo)completeEntry(b.dataset.undo,b.dataset.date,true);if(b.dataset.move)moveEntry(b.dataset.move,b.dataset.date);if(['generatePlan','generateTop'].includes(b.id)){document.querySelector('[data-view="planning"]').click();generatePlan()}})
el('taskForm').addEventListener('submit',e=>{e.preventDefault();let id=el('taskId').value,t=id?data.tasks.find(x=>x.id===id):{id:uid()};Object.assign(t,{name:el('taskName').value.trim(),category:el('taskCategory').value,duration:+el('taskDuration').value,frequency:el('taskFrequency').value,priority:+el('taskPriority').value,lastDone:el('taskLastDone').value||null,withKids:el('taskWithKids').checked,withoutKids:el('taskWithoutKids').checked,notes:el('taskNotes').value.trim()});if(!t.withKids&&!t.withoutKids){toast('Kies minstens één weektype.');return}if(!id)data.tasks.push(t);closeTask();save();toast('Taak opgeslagen.')})
el('deleteTask').onclick=()=>{let id=el('taskId').value;if(confirm('Deze taak definitief verwijderen?')){data.tasks=data.tasks.filter(t=>t.id!==id);closeTask();save()}}
el('taskSearch').oninput=renderTasks;el('categoryFilter').onchange=renderTasks;el('weekStart').onchange=()=>{el('planWeekType').value=currentWeekType(el('weekStart').value);renderPlan()};el('planWeekType').onchange=()=>{};el('currentWeekType').onchange=e=>{data.settings.weekType=e.target.value;save()};el('alternateWeeks').onchange=e=>{data.settings.alternate=e.target.checked;save()};el('capacityInputs').onchange=e=>{if(e.target.dataset.cap!==undefined){data.settings.capacities[+e.target.dataset.cap]=+e.target.value;save()}}
el('exportData').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='weekkompas-backup-'+iso(new Date())+'.json';a.click();URL.revokeObjectURL(a.href)}
el('importData').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.tasks||!x.settings)throw 0;data=x;save();toast('Back-up geïmporteerd.')}catch{toast('Dit is geen geldige Weekkompas-back-up.')}};r.readAsText(f)}
el('resetDemo').onclick=()=>{if(confirm('Alle lokale gegevens vervangen door voorbeeldgegevens?')){data=demo();save()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;el('installBtn').classList.remove('hidden')});el('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;el('installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderAll();